### ISSUE TITLE
does this plugin work without next export too?

### ISSUE THREAD

**Issue by hosnas** [dc7290/next-export-optimize-images#105]
I just want to use it in normal cases when we don't want to use next export.

**Comment by dc7290** [comment]
@hosnas 

I see!
I hadn't envisioned that usage.
Am I correct that you want to optimize the images when you do the `next build`?

Also, can you tell me why you don't want to use the default image optimization server feature of Next.js in that case?

**Comment by hosnas** [comment]
@dc7290 

Because we use some of the things that aren't supported with next export.

And still we want to optimize the images in the build time. so that we can use the following option of next js in pages that we don't want runtime js:

`export const config = {
   unstable_runtimeJS: false,
 };`

**Comment by dc7290** [comment]
@hosnas 

First, let me see if my understanding is correct.

```js
export const config = { unstable_runtimeJS: false, };
```
I assume that applying this setting means that you are not using a lazy load or placeholder image in `next/image`.
In that case, it would be the same as using a noscript rendered by `next/image`.
But you still need to use `next/image`?

**Comment by hosnas** [comment]
yes @dc7290 

I want to use next/image with that config, and only want to show user the optimized image. I dont need lazy load and placeholders.

**Comment by dc7290** [comment]
@hosnas 

I ask because I am not familiar with `unstable_runtimeJS`.

`export const config = { unstable_runtimeJS: false, };`
If I use this one, will the server side JS also stop working?

If not, then the Next.js image API not working is most likely a bug!

If you don't mind, could you create a simple demo app about `unstable_runtimeJS` and share the repository with us?

**Comment by itsmejoeeey** [comment]
@dc7290 At least in my case, the reason for not wanting to use `next export` is because:

1. I require a feature from the default Next.js server `next start` (such as rewrites or incremental static regeneration).
2. I redeploy often and don't want my first users to wait while images are optimized at runtime (as would happen by default with the Next.js implementation). 

-----

This plugin seems to suit my needs. I managed to get this plugin working without using `next export`.

To accomplish this I did:

1. Added the following to my `next.config.js` file

```
    distDir: "_next",
```

2. Had the following in my `export-images.config.js` file

```
/**
 * @type {import('next-export-optimize-images').Config}
 */
const config = {
    imageDir: '../_next/static/chunks/images',
    outDir: 'public'
}

module.exports = config
```

This works and provides me with optimized images when running:
`next build && next-export-optimize-images && next start`.

**Comment by itsmejoeeey** [comment]
@dc7290 At least in my case, the reason for not wanting to use `next export` is because:

1. I require a feature from the default Next.js server `next start` (such as rewrites or incremental static regeneration). I realize I could do rewriting though a reverse proxy (such as `nginx`), but I am not for the moment.
2. I redeploy often and don't want my first users to wait while images are optimized at runtime (as would happen by default with the Next.js implementation). 

-----

This plugin seems to suit my needs. I managed to get this plugin working without using `next export`.

To accomplish this I did:

1. Added the following to my `next.config.js` file

```
    distDir: "_next",
```

2. Had the following in my `export-images.config.js` file

```
/**
 * @type {import('next-export-optimize-images').Config}
 */
const config = {
    imageDir: '../_next/static/chunks/images',
    outDir: 'public'
}

module.exports = config
```

This works and provides me with optimized images when running:
`next build && next-export-optimize-images && next start`.

**Limitations:**
Currently the download path for external images is hardcoded (see: https://github.com/dc7290/next-export-optimize-images/blob/e4ec81e75dd781c950eaaee3988da16522c08975/src/image.tsx#L68). This means in cases where the image is not optimized, such as when:

> The following images is in a non-optimized format and a simple copy was applied.

The image will not be served/display correctly.

**Comment by dc7290** [comment]
@itsmejoeeey 

Thank you!
I see. So that's one way to use it when the build cycle is short.

I will check the operation just to be sure, and if it looks okay, I will provide it as a tip in the documentation.

**Comment by itsmejoeeey** [comment]
I'm in the process of opening a PR to add a new `externalOutputDir` flag to prevent the issue I mentioned above in 'Limitations'. This would allow the user to set the directory the external images are downloaded to.

It is also worth nothing that in my deployment I created a symlink from `.next` to `_next`. This solved another issue I had with `custom-optimized-images.nd.json` failing to be created if `.next` doesn't exist (because of the changed `distDir` we defined in `next.config.js`).

**Comment by dc7290** [comment]
@itsmejoeeey 
この設定が良さそうであれば、公式のオプションとして提供してもいいのかもしれませんね。
例えば、以下のように。
```js
/**
 * @type {import('next-export-optimize-images').Config}
 */
const config = {
  mode: 'build' // 'export' or 'build'
}

module.exports = config
```

**Comment by cronin4392** [comment]
I would love this option as well. My use case is I am using remote images from a provider that expires the image URLs after 2 hours. My images are coming from Airtable ([they talk about asset expiration here](https://support.airtable.com/docs/airtable-attachment-url-behavior)) but I also discovered Notion does this as well ([`expiry_time` in their API docs](https://developers.notion.com/reference/file-object)).

**Comment by MarcoDeJong** [comment]
I want to optimize images at build time as well, as I am working on a readonly filesystem. Still using SSR, but can't write to .next/cache folder, so image optimizations runtime are non-existent
