### ISSUE TITLE
Blur only on string entries

### ISSUE THREAD

**Issue by honzapatCZ** [dc7290/next-export-optimize-images#560]
Hello
Even from source the blur uri is only getting generated when the src is string. Is there any reason why it's not generated for normal require/static imports? It would be super helpful if it would and there doesnt seem to be any technical problem.

**To Reproduce**
1. Use an imported/required image and try to use the placeholder=blur
3. Notice no blur

**Expected behavior**
Blurred version of image

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave - Chromium
 - Version: latest

**Comment by dc7290** [comment]
This is because Next.js generates a placeholder image!

Specifically, this is specified in the following code.
https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/get-img-props.ts#L368
This `staticImageData.blurDataURL` is generated when importing an image when using Next.js and is a very small version of the original image.

Therefore, this library basically aims to be compliant with Next.js functionality, so the library does not generate a placeholder image using this.

Also, when using this library for static generation, the time that the placeholder is displayed is very small and the original image will be displayed immediately, so perhaps this is an option that is not necessary. (There are no plans to discontinue the placeholder prop in the components provided by this library in the future).
