### ISSUE TITLE
Part of `export-images.config.js` does not work

### ISSUE THREAD

**Issue by dc7290** [dc7290/next-export-optimize-images#612]
We are currently investigating, but the following features do not seem to be working.

- basePath
- sourceImageParser
- convertFormat
- imageDir
- externalImageDir
- filenameGenerator

Perhaps there is a phenomenon where `export-images.config.js` cannot be loaded during the HTML generation phase in the `next build`.

**Comment by dc7290** [comment]
Correcting...

**Comment by dc7290** [comment]
Preparing for release...

**Comment by cotwitch** [comment]
@dc7290 Hi d-suke! 

I would like to kindly ask you, are you pretty sure that is it really fixed? (Or is `basePath` config property working as expected?)

I'm asking, because when I'm using (slightly outdated?) example from `https://github.com/dc7290/next-export-optimize-images/examples/common` and making appropriate changes (due to last Next.js changes, see below), it's unfortunately not working for me :( 

My intention is to build simple static Next.js export which could be running on a simple static http server **in subdirectory** at ie. `http://hostname.tld/out/` .

So, I'm using `basePath` in `next.config.js`, but `basePath` from `export-images.config.js` is appearing to be ignored (?).

Changes I'm doing (complete diff is included at bottom):
- `next.config.js` - adding `output: 'export'` (as stated in [Next.js documentation](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#configuration))
- `next.config.js` - adding `basePath: '/out'`
- `package.json` - removing `next export && ` (as it's not needed anymore)
- `package.json` - forcing `next-export-optimize-images` to exact version `3.1.0` (which should be fine)

I'm also creating a config file `export-images.config.js` in project's root containing only following:
```
const config = {
  basePath: "/out",
};
module.exports = config;
```
So, the value exactly matches the very same as in `next.config.js`.

Then, when I run `generate` script, Next.js builds ok, but when comes to `next-export-optimize-images` I got many following errors:
```
[Error: ENOENT: no such file or directory, open '/private/tmp/next-export-optimize-images/examples/common/out/out/_next/static/media/img.8a5ad2fe.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/private/tmp/next-export-optimize-images/examples/common/out/out/_next/static/media/img.8a5ad2fe.png'
}
```
(so, problem from my point of view is "doubled" `/out/out/`, which should be just `/out/`)

And now - why I think that `basePath` config value is not working is - when I change `basePath` in `export-images.config.js` to any other value - nothing happens (!) :( 

I'm getting the exactly same errors as before (still getting `/out/out/` in output - instead of `/changed/out/` or `/out/changed/`).

If I'm doing anything wrong, please, let me know. 
(Possibly, if it's completely different issue than I'm currently writing to, I could create separate issue of course.)

It would be great, if you could update the example to reflect last changes (of Nextj.js).

Super cool would be, if you could add another working example using `basePath` (at Next.js and next-export-optimize-images configs).

Kindly thank you for any help.

Best regards

---

Changes I'm doing after cloning:
```
diff --git a/examples/common/next.config.js b/examples/common/next.config.js
index 9df4b8d..cfc1db9 100644
--- a/examples/common/next.config.js
+++ b/examples/common/next.config.js
@@ -4,6 +4,8 @@ const withExportImages = require('next-export-optimize-images')
  * @type {import('next').NextConfig}
  */
 const config = {
+  output: 'export',
+  basePath: '/out',
   reactStrictMode: true,
   trailingSlash: true,
   eslint: {
diff --git a/examples/common/package.json b/examples/common/package.json
index 5d72c5a..0bc8c1e 100644
--- a/examples/common/package.json
+++ b/examples/common/package.json
@@ -4,14 +4,14 @@
   "scripts": {
     "dev": "next dev",
     "build": "next build",
-    "generate": "yarn build && next export && next-export-optimize-images",
+    "generate": "yarn build && next-export-optimize-images",
     "lint": "next lint . --cache"
   },
   "dependencies": {
     "next": "latest",
     "react": "latest",
     "react-dom": "latest",
-    "next-export-optimize-images": "latest"
+    "next-export-optimize-images": "3.1.0"
   },
   "devDependencies": {}
 }
```
Creating file `export-images.config.js` containing:
```
const config = {
  basePath: "/out",
};
module.exports = config;
```

**Comment by dc7290** [comment]
We have confirmed that the problem is recurring here.
We are currently investigating.

**Comment by cotwitch** [comment]
@dc7290 🥳🎉 Kindly thank you, sir 🎩
