### ISSUE TITLE
image not load

### ISSUE THREAD

**Issue by behnam-maqsudi** [dc7290/next-export-optimize-images#80]
i can not load images
true image address is https://strapi.zabanshenas.com/uploads/globe_b3ea0f1158.svg
but package generate some text like that
/_next/static/chunks/images/https://strapi.zabanshenas.com/uploads/globe_b3ea0f1158_640_75.svg 640w, 

how fix this
![image](https://user-images.githubusercontent.com/40948849/172420169-a439c639-cea9-444e-9a2f-77c69e1d20ed.png)

![image](https://user-images.githubusercontent.com/40948849/172420288-706b353d-d3ae-4641-a113-7d91a6c6273b.png)

![image](https://user-images.githubusercontent.com/40948849/172420416-b5b1ef6b-798d-4504-b68b-5529756ea95a.png)

**Comment by dc7290** [comment]
@benamm 

Thanks for reporting the bug!

This happens because the library aliases all `next/image` to "components that optimize images at build time".

If you have more than one pattern of image usage in your project, you can use the

1. Optimize images at build time
2. Use external images

You must pass the loader separately, as described in this document.
https://next-export-optimize-images.vercel.app/docs/examples#use-nextimage-separately-from-image-components-to-be-optimized-at-build-time

I have not been able to clearly document this usage, so I will add it to the Q&A section.

If you have any other questions, please comment.
